#!/bin/bash

if git log -1 --pretty='format:%s'|grep 'wip' >/dev/null;then
   echo 'this branch is wip'
   exit 1
fi

if git config 'prove.command' && ! eval $(git config 'prove.command');then
 exit 1
fi
