#!/bin/bash

if test "$(git symbolic-ref HEAD --short)" == "master";then
    echo -e "this is master"
fi

git diff-index --cached --name-only HEAD | grep '.php$' | xargs grep -l . 2>/dev/null | xargs -n 1 php -l
if test $? -ne 0; then
    echo "error!"
    exit 1
fi
