#!/bin/bash

if test "$(git symbolic-ref HEAD --short 2>/dev/null)" == "master";then
    echo -e "this is master"
fi

git diff-index --cached --name-only HEAD | grep '.php$' | xargs -n '\n' grep -l . | xargs -n 1 php -l 1>/dev/null
if test $? -ne 0; then
    echo "php error!"
    exit 1
fi
