#!/bin/bash

if git log -1 --pretty='format:%s'|grep 'wip' >/dev/null;then
   echo 'this branch is wip'
   exit 1
fi

echo prove start
if [ -n "${PROVE_COMMAND}" ] && ! eval ${PROVE_COMMAND};then
 exit 1
fi
