#!/bin/bash

if cat $1 | grep -q '^refs #[0-9]\|^wip';then exit;fi
if [ "$2" != "message" ];then exit;fi
if [ -e .git/MERGE_HEAD ];then exit;fi
branch=$(git rev-parse --abbrev-ref HEAD)
if [ "$branch" = "HEAD" ];then
 if [ -e '.git/rebase-merge' ];then branch=$(<.git/rebase-merge/head-name)
 elif [ -e '.git/rebase-apply' ];then branch=$(<.git/rebase-apply/head-name)
 fi
fi
if ! echo $branch | grep -q '\(^\|_\)[0-9]\+_';then exit;fi
ret=$(echo $branch | sed 's/[^0-9]*\([0-9]*\)_.*/refs #\1/')
ret=$ret' '$(cat $1)
echo "$ret" > $1
